In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('/content/Housing.csv')
print("shape",df.shape)
df.head()

shape (545, 13)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [4]:
df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [5]:
df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.sort_values(by='price', ascending=True)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished

In [10]:
df.sort_values(by='price', ascending=False)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [11]:
df.sort_values(by=['area', 'bedrooms'], ascending=[True, True])

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
449,3150000,1650,3,1,2,no,no,yes,no,no,0,no,unfurnished
537,1890000,1700,3,1,2,yes,no,no,no,no,0,no,unfurnished
527,2275000,1836,2,1,1,no,no,yes,no,no,0,no,semi-furnished
271,4340000,1905,5,1,2,no,no,yes,no,no,0,no,semi-furnished
413,3430000,1950,3,2,2,yes,no,yes,no,no,0,yes,unfurnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
403,3500000,12944,3,1,1,yes,no,no,no,no,0,no,unfurnished
66,6930000,13200,2,1,1,yes,no,yes,yes,no,1,no,furnished
10,9800000,13200,3,1,2,yes,no,yes,no,yes,2,yes,furnished
125,5943000,15600,3,1,1,yes,no,no,no,yes,2,no,semi-furnished
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished

In [12]:
df[df['price'] > 5000000]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,5040000,7600,4,1,2,yes,no,no,no,yes,2,no,furnished
191,5040000,10700,3,1,2,yes,yes,yes,no,no,0,no,semi-furnished
192,5040000,6600,3,1,1,yes,yes,yes,no,no,0,yes,furnished
193,5033000,4800,2,1,1,yes,yes,yes,no,no,0,no,semi-furnished
194,5005000,8150,3,2,1,yes,yes,yes,no,no,0,no,semi-furnished

In [13]:
df[df['bedrooms'] == 3]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished
10,9800000,13200,3,1,2,yes,no,yes,no,yes,2,yes,furnished
14,9240000,7800,3,2,2,yes,no,no,no,no,0,yes,semi-furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
533,2100000,2400,3,1,2,yes,no,no,no,no,0,no,unfurnished
537,1890000,1700,3,1,2,yes,no,no,no,no,0,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [14]:
df[df['bathrooms'] >= 2]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
413,3430000,1950,3,2,2,yes,no,yes,no,no,0,yes,unfurnished
446,3150000,3986,2,2,1,no,yes,yes,no,no,1,no,unfurnished
499,2660000,3630,3,3,2,no,yes,no,no,no,0,no,unfurnished
509,2590000,3600,2,2,2,yes,no,yes,no,no,1,no,furnished
523,2380000,2787,4,2,2,yes,no,no,no,no,0,no,furnished

In [15]:
df[df['furnishingstatus'] == 'furnished']

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
509,2590000,3600,2,2,2,yes,no,yes,no,no,1,no,furnished
512,2520000,3000,2,1,2,yes,no,no,no,no,0,no,furnished
522,2380000,2475,3,1,2,yes,no,no,no,no,0,no,furnished
523,2380000,2787,4,2,2,yes,no,no,no,no,0,no,furnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished

In [16]:
df[df['parking'] == 0]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished
14,9240000,7800,3,2,2,yes,no,no,no,no,0,yes,semi-furnished
26,8463000,6000,3,2,4,yes,yes,yes,no,yes,0,yes,semi-furnished
40,7875000,6550,3,1,2,yes,no,yes,no,yes,0,yes,furnished
41,7840000,6360,3,2,4,yes,no,no,no,yes,0,yes,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
538,1890000,3649,2,1,1,yes,no,no,no,no,0,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [17]:
df['Price_per_sqft'] = df['price'] / df['area']

In [18]:
def area_category(x):
    if x < 1000:
        return 'Small'
    elif 1000 <= x <= 2000:
        return 'Medium'
    else:
        return 'Large'

df['Area_Category'] = df['area'].apply(area_category)

In [19]:
df[['area', 'Area_Category']].head()

   area Area_Category
0  7420         Large
1  8960         Large
2  9960         Large
3  7500         Large
4  7420         Large

In [20]:
df['Price_Rank'] = df['price'].rank(ascending=False)

In [21]:
df['Area_Rank'] = df['area'].rank(ascending=False)

In [22]:
df['Rank_within_furnish'] = df.groupby('furnishingstatus')['price'].rank(ascending=False)

In [25]:
df.nlargest(5, 'price')

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,Price_per_sqft,Area_Category,Price_Rank,Area_Rank,Rank_within_furnish
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792.452830,Large,1.0,73.5,1.0
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1367.187500,Large,2.5,30.0,2.0
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229.919679,Large,2.5,19.0,1.0
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628.666667,Large,4.0,66.5,3.0
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1537.735849,Large,5.0,73.5,4.0

In [26]:
df.groupby('furnishingstatus')['price'].mean()

furnishingstatus
furnished         5.495696e+06
semi-furnished    4.907524e+06
unfurnished       4.013831e+06
Name: price, dtype: float64

In [27]:
df.groupby('bedrooms')['price'].mean()

bedrooms
1    2.712500e+06
2    3.632022e+06
3    4.954598e+06
4    5.729758e+06
5    5.819800e+06
6    4.791500e+06
Name: price, dtype: float64

In [28]:
df['furnishingstatus'].value_counts()

furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64

In [29]:
df.groupby('parking')['area'].mean()

parking
0    4501.120401
1    5576.357143
2    6226.379630
3    7178.333333
Name: area, dtype: float64

In [30]:
df.groupby('bedrooms')['price'].max()

bedrooms
1     3150000
2     7070000
3    12250000
4    13300000
5    10150000
6     6083000
Name: price, dtype: int64

In [31]:
house_price = df['price'].quantile(0.95)
df[df['price'] >= house_price]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,Price_per_sqft,Area_Category,Price_Rank,Area_Rank,Rank_within_furnish
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished,1792.452830,Large,1.0,73.5,1.0
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished,1367.187500,Large,2.5,30.0,2.0
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished,1229.919679,Large,2.5,19.0,1.0
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished,1628.666667,Large,4.0,66.5,3.0
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished,1537.735849,Large,5.0,73.5,4.0
5,10850000,7500,3,3,1,yes,no,yes,no,yes,2,yes,semi-furnished,1446.666667,Large,6.0,66.5,2.0
6,10150000,8580,4,3,4,yes,no,no,no,yes,2,yes,semi-furnished,1182.983683,Large,7.5,35.5,3.0
7,10150000,16200,5,3,2,yes,no,no,no,no,0,no,unfurnished,626.543210,Large,7.5,1.0,1.0
8,9870000,8100,4,1,2,yes,yes,yes,no,yes,2,yes,furnished,1218.518519,Large,9.0,49.0,5.0
9,9800000,5750,3,2,4,yes,yes,no,no,yes,1,yes,unfurnished,1704.347826,Large,10.5,198.0,2.0
10,9800000,13200,3,1,2,yes,no,yes,no,yes,2,yes,furnished,742.424242,Large,10.5,3.5,6.0
11,9681000,6000,4,3,2,yes,yes,yes,yes,no,2,no,semi-furnished,1613.500000,Large,12.0,169.5,4.0
12,9310000,6550,4,2,2,yes,no,no,no,yes,1,yes,semi-furnished,1421.374046,Large,13.0,118.5,5.0
13,9240000,3500,4,2,2,yes,no,no,yes,no,2,no,furnished,2640.000000,Large,14.5,423.5,7.0
14,9240000,7800,3,2,2,yes,no,no,no,no,0,yes,semi-furnished,1184.615385,Large,14.5,58.5,6.0
15,9100000,6000,4,1,2,yes,no,yes,no,no,2,no,semi-furnished,1516.666667,Large,16.5,169.5,7.0
16,9100000,6600,4,2,2,yes,yes,yes,no,yes,1,yes,unfurnished,1378.787879,Large,16.5,113.0,3.0
17,8960000,8500,3,2,4,yes,no,no,no,yes,2,no,furnished,1054.117647,Large,18.0,38.0,8.0
18,8890000,4600,3,2,2,yes,yes,no,no,yes,2,no,furnished,1932.608696,Large,19.0,271.0,9.0
19,8855000,6420,3,2,2,yes,no,no,no,yes,1,yes,semi-furnished,1379.283489,Large,20.0,132.5,8.0
20,8750000,4320,3,1,2,yes,no,yes,yes,no,2,no,semi-furnished,2025.462963,Large,21.0,304.5,9.0
21,8680000,7155,3,2,1,yes,yes,yes,no,yes,2,no,unfurnished,1213.137666,Large,22.0,83.0,4.0
22,8645000,8050,3,1,1,yes,yes,yes,no,yes,1,no,furnished,1073.913043,Large,23.5,52.5,10.5
23,8645000,4560,3,2,2,yes,yes,yes,no,yes,1,no,furnished,1895.833333,Large,23.5,274.0,10.5
24,8575000,8800,3,2,2,yes,no,no,no,yes,2,no,furnished,974.431818,Large,25.0,34.0,12.0
25,8540000,6540,4,2,2,yes,yes,yes,no,yes,2,yes,furnished,1305.810398,Large,26.0,121.0,13.0
26,8463000,6000,3,2,4,yes,yes,yes,no,yes,0,yes,semi-furnished,1410.500000,Large,27.0,169.5,10.0
27,8400000,8875,3,1,1,yes,no,no,no,no,1,no,semi-furnished,946.478873,Large,30.0,33.0,12.0
28,8400000,7950,5,2,2,yes,no,yes,yes,no,2,no,unfurnished,1056.603774,Large,30.0,57.0,5.5
29,8400000,5500,4,2,2,yes,no,yes,no,yes,1,yes,semi-furnished,1527.272727,Large,30.0,208.0,12.0
30,8400000,7475,3,2,4,yes,no,no,no,yes,2,no,unfurnished,1123.745819,Large,30.0,69.0,5.5
31,8400000,7000,3,1,4,yes,no,no,no,yes,2,no,semi-furnished,1200.000000,Large,30.0,89.0,12.0

In [32]:
Q1 = df['Price_per_sqft'].quantile(0.25)
Q3 = df['Price_per_sqft'].quantile(0.75)
IQR = Q3 - Q1
upper = Q3 + 1.5 * IQR

df[df['Price_per_sqft'] > upper]

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus,Price_per_sqft,Area_Category,Price_Rank,Area_Rank,Rank_within_furnish
13,9240000,3500,4,2,2,yes,no,no,yes,no,2,no,furnished,2640.000000,Large,14.5,423.5,7.0
18,8890000,4600,3,2,2,yes,yes,no,no,yes,2,no,furnished,1932.608696,Large,19.0,271.0,9.0
20,8750000,4320,3,1,2,yes,no,yes,yes,no,2,no,semi-furnished,2025.462963,Large,21.0,304.5,9.0
23,8645000,4560,3,2,2,yes,yes,yes,no,yes,1,no,furnished,1895.833333,Large,23.5,274.0,10.5
108,6107500,3240,4,1,3,yes,no,no,no,no,1,no,semi-furnished,1885.030864,Large,109.0,452.0,38.0
157,5495000,2817,4,2,2,no,yes,yes,no,no,1,no,furnished,1950.656727,Large,158.5,505.0,62.0
271,4340000,1905,5,1,2,no,no,yes,no,no,0,no,semi-furnished,2278.215223,Medium,273.0,542.0,132.0
282,4270000,2175,3,1,2,no,yes,yes,no,yes,0,no,unfurnished,1963.218391,Large,282.5,529.0,54.5
302,4200000,2145,3,1,3,yes,no,no,no,no,1,yes,unfurnished,1958.041958,Large,296.0,533.5,58.5
345,3850000,2015,3,1,2,yes,no,yes,no,no,0,yes,semi-furnished,1910.669975,Large,344.0,538.0,172.5
449,3150000,1650,3,1,2,no,no,yes,no,no,0,no,unfurnished,1909.090909,Medium,450.0,545.0,113.0